export const mockObjectCountries = {
  EU: {
    countries: [
      "Sweden",
      "Spain",
      "Slovenia",
      "Slovakia",
      "Romania",
      "Portugal",
      "Poland",
      "Netherlands",
      "Malta",
      "Luxembourg",
      "Lithuania",
      "Latvia",
      "Italy",
      "Isle of Man",
      "Ireland",
      "Hungary",
      "Greece",
      "Gibraltar",
      "Germany",
      "French Guiana",
      "France",
      "Finland",
      "Estonia",
      "Denmark",
    ],
    population: 448196830,
    languages: {
      pl: {
        countries: {
          area: 312679,
          countries: ["POL"],
          name: "język polski",
          population: 37950802,
        },
        population: 37950802,
        area: 312679,
        name: "język polski",
      },
    },
    currencies: [
      "Euro",
      "Bulgarian lev",
      "Croatian kuna",
      "Czech koruna",
      "Danish krone",
      "Gibraltar pound",
      "Hungarian forint",
    ],
  },
  NAFTA: {
    countries: ["United States of America", "Mexico", "Canada"],
    population: 496422114,
    languages: {
      en: {
        countries: {
          area: 19613761,
          countries: ["CAN", "USA"],
          name: "English",
          population: 367489361,
        },
        population: 367489361,
        area: 19613761,
        name: "English",
      },
      es: {
        countries: {
          area: 1964375,
          countries: ["MEX"],
          name: "Español",
          population: 128932753,
        },
        population: 128932753,
        area: 1964375,
        name: "Español",
      },
      fr: {
        countries: {
          area: 9984670,
          countries: ["CAN"],
          name: "français",
          population: 38005238,
        },
        population: 38005238,
        area: 9984670,
        name: "français",
      },
    },
    currencies: ["Canadian dollar", "Mexican peso", "United States dollar"],
  },
  AU: {
    countries: [],
    population: 0,
    languages: {},
    currencies: [],
  },
  other: {
    countries: [],
    population: 0,
    languages: {},
    currencies: [],
  },
};
